import type { IProject } from "./types";

export const PROJECTS: IProject[] = [
  {
    title: "Seidor Brasil",
    description:
      "Responsavel pelo desenvolvimento Front-end do Sistema, com integração com Back-end, realizando gestão de estado, formularios, regras de impostos, criação de componentes reutilizaveis.",
    technologies: [
      "React",
      "Next.js",
      "AWS",
      "API REST",
      "Styled Components",
      "Bibliotecas Internas",
      "DEV/Test/Homolog/Prod",
      "SCRUM",
      "Azure Pipelines",
      "Azure Devops",
    ],
    imageUrl: "/assets/cases/seidor.png",
    alt: "Projeto - Seidor Brasil",
    delay: "0.2s",
    status: "concluido",
  },
  {
    title: "Road Budget",
    description:
      "Projeto de planejamento de viagens Overland com calculo de rotas via Google Maps API e estimativa de custos.",
    technologies: [
      "React",
      "Vite",
      "Supabase",
      "JavaScript",
      "Styled Componentes",
      "Phosphor-icons",
      "Vercel",
      "CI/CD",
      "API's",
      "Google Maps API",
      "Prod",
    ],
    imageUrl: "/assets/cases/logo-skall.png",
    liveUrl: "#",
    alt: "Projeto - Road Budget",
    delay: "0.2s",
    status: "em-desenvolvimento",
  },
  {
    title: "Ceci Nutricionista",
    description: "Site desenvolvido para venda de Planos Nutricionais.",
    technologies: [
      "Vite",
      "React",
      "Styled Components",
      "Motion",
      "Phosphor-icons",
      "Vercel",
      "CI/CD",
      "Integrações",
      "Prod/Homolog",
    ],
    imageUrl: "/assets/cases/CE.png",
    githubUrl: "https://github.com/GustavoJorgge/ceci-nutri",
    liveUrl: "#",
    alt: "Projeto - Ceci Nutricionista",
    delay: "0.2s",
    status: "em-desenvolvimento",
  },

  {
    title: "Integração Voke",
    description:
      "Sustentação e Construção de Páginas que integram com CRM para geração de Leads, sustentação de Website Institucional.",
    technologies: [
      "Next.js",
      "Node.js",
      "API REST",
      "Marketing Cloud",
      "N8N",
      "Azure Pipelines",
      "AWS",
      "CI/CD",
      "SCRUM",
      "SEO",
      "CMS/STRAPI",
    ],
    imageUrl: "/assets/cases/Voke.png",
    liveUrl: "https://voke.tech",
    alt: "Projeto Integração Voke",
    delay: "0.4s",
    status: "concluido",
  },
];
